[package]
name = "dedup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasthash = "0.4.0"
memmap = "0.7.0"

[profile.release]
lto = "fat"
panic = "abort"
debug = true
codegen-units = 1
